# Generated by Django 4.1.6 on 2023-02-24 10:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0004_alter_favourite_article_alter_note_article'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='article.article'),
        ),
    ]
