# Generated by Django 4.1.6 on 2023-03-09 07:45

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0008_alter_article_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='content',
            field=tinymce.models.HTMLField(),
        ),
    ]
