# Generated by Django 4.1.6 on 2023-04-01 11:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Radical',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('radical', models.CharField(max_length=2)),
                ('radical_number', models.CharField(max_length=3)),
                ('number_of_stroke', models.CharField(max_length=2)),
                ('alternative', models.CharField(max_length=20)),
                ('meaning', models.CharField(max_length=50)),
                ('readings', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Kanji',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kanji', models.CharField(max_length=2)),
                ('onyomi', models.CharField(max_length=50)),
                ('kunyomi', models.CharField(max_length=100)),
                ('meaning', models.CharField(max_length=200)),
                ('examples', models.CharField(max_length=7000)),
                ('jlpt_level', models.CharField(max_length=2)),
                ('no_of_strokes', models.CharField(max_length=5)),
                ('radical', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='kanji.radical')),
            ],
        ),
    ]
