# Generated by Django 4.1.6 on 2023-09-05 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kanji', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='radical',
            name='number_of_stroke',
            field=models.IntegerField(max_length=2),
        ),
        migrations.AlterField(
            model_name='radical',
            name='radical_number',
            field=models.IntegerField(),
        ),
    ]
