# Generated by Django 4.1.6 on 2023-09-05 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kanji', '0002_alter_radical_number_of_stroke_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='radical',
            name='number_of_stroke',
            field=models.IntegerField(),
        ),
    ]
