# Generated by Django 4.1.6 on 2023-09-11 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kanji', '0003_alter_radical_number_of_stroke'),
    ]

    operations = [
        migrations.AddField(
            model_name='kanji',
            name='parts',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
