# Generated by Django 4.1.6 on 2024-06-28 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kanji', '0005_alter_kanji_parts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kanji',
            name='no_of_strokes',
            field=models.IntegerField(max_length=5),
        ),
    ]
