# Generated by Django 4.1.6 on 2024-06-29 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kanji', '0006_alter_kanji_no_of_strokes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kanji',
            name='no_of_strokes',
            field=models.IntegerField(),
        ),
    ]
