# Generated by Django 4.1.6 on 2024-07-01 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kanji', '0007_alter_kanji_no_of_strokes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kanji',
            name='no_of_strokes',
            field=models.IntegerField(default=5),
        ),
    ]
