# Generated by Django 4.1.6 on 2023-02-24 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='writer',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
