# Generated by Django 4.1.6 on 2023-02-24 07:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_book_writer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='writer',
            new_name='author',
        ),
    ]
