# Generated by Django 4.1.6 on 2023-02-24 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0005_chapter_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chapter',
            name='ch_no',
            field=models.CharField(max_length=10),
        ),
    ]
