# Generated by Django 4.1.6 on 2023-02-27 05:17

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0007_rename_ch_no_chapter_chapter_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chapter',
            name='content',
            field=tinymce.models.HTMLField(),
        ),
    ]
