# Generated by Django 4.1.6 on 2023-03-08 07:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0010_alter_book_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='favourite',
            name='book',
        ),
        migrations.RemoveField(
            model_name='note',
            name='book',
        ),
        migrations.AddField(
            model_name='favourite',
            name='chapter',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='favourites', to='book.chapter'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='note',
            name='chapter',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='book.chapter'),
            preserve_default=False,
        ),
    ]
