# Generated by Django 4.1.6 on 2024-10-25 04:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0013_remove_favourite_meaning_favourite_no'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='user',
            new_name='creator',
        ),
    ]
